### PR TITLE
travis deploy branch master

### PR DESCRIPTION
**Pull request by pgdr**
I hope this will make travis deploy master to pypi

### CODE REVIEW

**Comment by pgdr** [comment]
@semafor can you add user `friskby` to [friskby-controlpanel](https://pypi.python.org/pypi/friskby-controlpanel/0.5.1) as a _maintainer_?  And while you're add it, can you add myself, preferably as owner?

**Comment by semafor** [comment]
> can you add user friskby to friskby-controlpanel as a maintainer? And while you're add it, can you add myself, preferably as owner

Done and done!

**Comment by pgdr** [comment]
Thanks!

**Comment by pgdr** [comment]
It seemed to work (but none deployed since the version number existed).

**Pull request merged**
